lzx:
  mysql:
#    ip: 192.168.186.128
    ip: 192.168.4.132

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${lzx.mysql.ip}:3306/hl_demo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: qq123123
#    打开mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  tokenExpire: 86400