spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.4.132:3306/hl_demo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: qq123123
