lzx:
  mysql:
    ip: 192.168.186.128

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${lzx.mysql.ip}:3306/hl_demo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: qq123123
